name: Lark notification

# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on:
  push:
  issues:
  pull_request:
  discussion:
  issue_comment:
  discussion_comment:
  pull_request_review_comment:
  release:
    types:
      - published

jobs:
  send-Lark-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Event Message serialization
        id: message
        run: |
          YAML=$(
          cat <<JSON | deno run --allow-all .github/scripts/transform-message.ts
          ${{ toJSON(github) }}
          JSON
          )
          {
            echo 'content<<EOF'
            echo "$YAML"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Send message to Lark
        if: ${{ contains(steps.message.outputs.content, ':') }}
        uses: Open-Source-Bazaar/feishu-action@v3
        with:
          url: ${{ secrets.LARK_CHATBOT_HOOK_URL }}
          msg_type: interactive
          content: |
            ${{ steps.message.outputs.content }}
